title: Contributor Book
# description: 

# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nushell
url: "https://github.com/nushell"
google_analytics: UA-69474134-2

# Build settings
theme: jekyll-theme-midnight
